### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by nec-bis** [genebean/genebean-nxlog#12]
Hi there,

this module requires chocolatey/chocolatey which in turn requires the now deprecated badgerious/windows_env is it possible to update the dependencies to use puppetlabs/chocolatey instead? It should be an in place upgrade.

**Comment by genebean** [comment]
Certainly! I'll post an update tonight or tomorrow. @thespain is working on a bigger update in #11 too BTW.

**Comment by genebean** [comment]
I did the update today and pushed them to a branch but wasn't able to get a release cut due to wanting to check to make sure things were working well even though my tests are jacked up right now. I should be able to get it out tomorrow though.

**Comment by genebean** [comment]
Just pushed 1.4.2 to fix this

**Comment by nec-bis** [comment]
Excellent work Gene. Thank you. 

I won't be able to test till Tuesday but I'm sure it's fine.

⁣Sent from TypeApp ​
